authorization:
  enabled: false
  service-name: "authorization-server"
  connection:
    url: "http://localhost:8090/api/v1/authorize"
    read-timeout: "5s"
    connect-timeout: "5s"
    max-attempts: 3


spring:
  datasource:
    url: jdbc:postgresql://localhost:3000/smack
    username: smack
    password: smack
  jpa:
    hibernate:
      ddl-auto: create-drop # In production should not be set.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect